import mysql from 'mysql2/promise';
declare const _default: import("drizzle-orm/mysql2").MySql2Database<{
    postsRelations: import("drizzle-orm").Relations<"posts", {
        user: import("drizzle-orm").One<"users", true>;
        postsToHashtags: import("drizzle-orm").Many<"posts_to_hashtags">;
    }>;
    hashtagRelations: import("drizzle-orm").Relations<"hashtags", {
        postsToHashtags: import("drizzle-orm").Many<"posts_to_hashtags">;
    }>;
    postsToHashtagsRelations: import("drizzle-orm").Relations<"posts_to_hashtags", {
        post: import("drizzle-orm").One<"posts", true>;
        hashtag: import("drizzle-orm").One<"hashtags", true>;
    }>;
    usersRelations: import("drizzle-orm").Relations<"users", {
        posts: import("drizzle-orm").Many<"posts">;
        followers: import("drizzle-orm").Many<"follows">;
        followings: import("drizzle-orm").Many<"follows">;
    }>;
    followsRelations: import("drizzle-orm").Relations<"follows", {
        follower: import("drizzle-orm").One<"users", true>;
        following: import("drizzle-orm").One<"users", true>;
    }>;
    users: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
        name: "users";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "id";
                tableName: "users";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            nick: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "nick";
                tableName: "users";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            password: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "password";
                tableName: "users";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            provider: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "provider";
                tableName: "users";
                dataType: "string";
                columnType: "MySqlEnumColumn";
                data: "local" | "kakao";
                driverParam: string;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: ["local", "kakao"];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            createdAt: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "created_at";
                tableName: "users";
                dataType: "string";
                columnType: "MySqlDateTimeString";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            updatedAt: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "updated_at";
                tableName: "users";
                dataType: "string";
                columnType: "MySqlDateTimeString";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            deletedAt: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "deleted_at";
                tableName: "users";
                dataType: "string";
                columnType: "MySqlDateTimeString";
                data: string;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
        };
        dialect: "mysql";
    }>;
    posts: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
        name: "posts";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "id";
                tableName: "posts";
                dataType: "number";
                columnType: "MySqlInt";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: true;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            userId: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "user_id";
                tableName: "posts";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            content: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "content";
                tableName: "posts";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            img: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "img";
                tableName: "posts";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            createdAt: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "created_at";
                tableName: "posts";
                dataType: "string";
                columnType: "MySqlDateTimeString";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            updatedAt: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "updated_at";
                tableName: "posts";
                dataType: "string";
                columnType: "MySqlDateTimeString";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            deletedAt: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "deleted_at";
                tableName: "posts";
                dataType: "string";
                columnType: "MySqlDateTimeString";
                data: string;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
        };
        dialect: "mysql";
    }>;
    hashtags: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
        name: "hashtags";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "id";
                tableName: "hashtags";
                dataType: "number";
                columnType: "MySqlInt";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: true;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            title: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "title";
                tableName: "hashtags";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            createdAt: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "created_at";
                tableName: "hashtags";
                dataType: "string";
                columnType: "MySqlDateTimeString";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
        };
        dialect: "mysql";
    }>;
    postsToHashtags: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
        name: "posts_to_hashtags";
        schema: undefined;
        columns: {
            postId: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "post_id";
                tableName: "posts_to_hashtags";
                dataType: "number";
                columnType: "MySqlInt";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            hashtagId: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "hashtag_id";
                tableName: "posts_to_hashtags";
                dataType: "number";
                columnType: "MySqlInt";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
        };
        dialect: "mysql";
    }>;
    follows: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
        name: "follows";
        schema: undefined;
        columns: {
            followerId: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "follower_id";
                tableName: "follows";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            followingId: import("drizzle-orm/mysql-core").MySqlColumn<{
                name: "following_id";
                tableName: "follows";
                dataType: "string";
                columnType: "MySqlVarChar";
                data: string;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
        };
        dialect: "mysql";
    }>;
}> & {
    $client: mysql.Pool;
};
export default _default;
